context("lolly")
library(ggplot2)

test_that("lolly checks arguments properly", {
  data("MIsim", package = "rsimsum")
  s1 <- simsum(data = MIsim, estvarname = "b", true = 0.5, se = "se", methodvar = "method")
  expect_error(lolly(obj = MIsim))
  expect_error(lolly(obj = s1))
  expect_error(lolly(obj = s1, sstat = "BIAS"))
  expect_error(lolly(obj = s1, sstat = "nsim"))
  expect_error(lolly(obj = s1, sstat = "bias", level = 101))
  data("frailty", package = "rsimsum")
  sm <- multisimsum(data = frailty, par = "par", true = c(trt = -0.50, fv = 0.75), estvarname = "b", se = "se", methodvar = "model", by = "fv_dist")
  expect_error(lolly(obj = sm))
  expect_error(lolly(obj = sm, sstat = "BIAS"))
  expect_error(lolly(obj = sm, sstat = "nsim"))
  expect_error(lolly(obj = sm, sstat = "bias", level = 101))
})

test_that("lolly returns a ggplot object", {
  data("MIsim", package = "rsimsum")
  s <- simsum(data = MIsim, estvarname = "b", true = 0.5, se = "se", methodvar = "method")
  data("frailty", package = "rsimsum")
  sm <- multisimsum(data = frailty, par = "par", true = c(trt = -0.50, fv = 0.75), estvarname = "b", se = "se", methodvar = "model")
  expect_s3_class(lolly(s, sstat = "bias"), class = c("gg", "ggplot"))
  expect_s3_class(lolly(sm, sstat = "bias", par = "trt"), class = c("gg", "ggplot"))
})

test_that("lolly does not plot CI when simsum in called with mcse = FALSE", {
  data("MIsim", package = "rsimsum")
  s <- simsum(data = MIsim, estvarname = "b", true = 0.5, se = "se", methodvar = "method", mcse = FALSE)
  lolly(s, sstat = "bias")
  data("frailty", package = "rsimsum")
  sm <- multisimsum(data = frailty, par = "par", true = c(trt = -0.50, fv = 0.75), estvarname = "b", se = "se", methodvar = "model", mcse = FALSE)
  lolly(sm, sstat = "bias", par = "trt")
})

test_that("lolly works with 'by' factors", {
  data("relhaz", package = "rsimsum")
  s <- simsum(data = relhaz, estvarname = "theta", true = -0.5, se = "se", methodvar = "model", by = c("n", "baseline"))
  expect_warning(lolly(s, sstat = "bias"))
  expect_error(lolly(s, sstat = "bias", by = "random-name"))
  expect_s3_class(lolly(s, sstat = "bias", by = c("n", "baseline")), class = c("gg", "ggplot"))
  data("frailty", package = "rsimsum")
  sm <- multisimsum(data = frailty, par = "par", true = c(trt = -0.50, fv = 0.75), estvarname = "b", se = "se", methodvar = "model", by = "fv_dist")
  expect_warning(lolly(sm, sstat = "bias", par = "trt"))
  expect_error(lolly(sm, sstat = "bias", par = "trt", by = "random-name"))
  expect_s3_class(lolly(sm, sstat = "bias", par = "trt", by = "fv_dist"), class = c("gg", "ggplot"))
})

test_that("lolly works when changing graphical parameters", {
  data("MIsim", package = "rsimsum")
  s <- simsum(data = MIsim, estvarname = "b", true = 0.5, se = "se", methodvar = "method")
  lolly(s, sstat = "bias", gpars = list(target.shape = 1))
  lolly(s, sstat = "bias", gpars = list(target.colour = 2))
  lolly(s, sstat = "bias", gpars = list(segment.shape = 3))
  lolly(s, sstat = "bias", gpars = list(segment.colour = 4))
  lolly(s, sstat = "bias", gpars = list(low.end = 5))
  lolly(s, sstat = "bias", gpars = list(upp.end = 6))
  data("frailty", package = "rsimsum")
  sm <- multisimsum(data = frailty, par = "par", true = c(trt = -0.50, fv = 0.75), estvarname = "b", se = "se", methodvar = "model")
  lolly(sm, sstat = "bias", par = "trt", gpars = list(target.shape = 1))
  lolly(sm, sstat = "bias", par = "trt", gpars = list(target.colour = 2))
  lolly(sm, sstat = "bias", par = "trt", gpars = list(segment.shape = 3))
  lolly(sm, sstat = "bias", par = "trt", gpars = list(segment.colour = 4))
  lolly(sm, sstat = "bias", par = "trt", gpars = list(low.end = 5))
  lolly(sm, sstat = "bias", par = "trt", gpars = list(upp.end = 6))
})
